/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailclientapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ethenq
 */
public class FileSaver extends javax.swing.JDialog {

    private final int RET_CANCEL = 0;
    private final int RET_OK = 1;
    
    private File attachment;
    
    public String filePath;
    
    /**
     * Creates new form FileBrowser
     */
    public FileSaver(java.awt.Dialog parent, boolean modal, String file_path) {
        super(parent, modal);
        
        this.filePath = file_path;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(false);
                        dispose();
                    }
        });
        
        initComponents();
        
        // jFileChooser1.showSaveDialog(this);
        jFileChooser1.setApproveButtonText("Zapisz plik");
        jFileChooser1.setDialogTitle("Zapisz plik");
        
        // jFileChooser1.setCurrentDirectory(new File(filePath));
        
        jFileChooser1.setSelectedFile(new File(filePath));
        setVisible(true);
    }

    public File getAttachment()
    {
        return attachment;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

        if (evt.getActionCommand().equals("ApproveSelection"))
        {
            String copyPath = jFileChooser1.getSelectedFile().getAbsolutePath();
            
            System.out.println("Ścieżka źródłowa pliku załącznika: " + filePath);
            System.out.println("Ścieżka kopiowania pliku załącznika: " + copyPath);
            // this.attachment = jFileChooser1.getSelectedFile();
            
            try {
                FileInputStream fis = new FileInputStream(filePath);
                FileOutputStream fos = new FileOutputStream(copyPath);
                
                byte bytes[] = new byte[(int) new File(filePath).length()];
                
                try {
                    while (fis.read(bytes) > 0) {}

                    fos.write(bytes); 
                    fos.flush();
                    
                    fis.close();
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(FileSaver.class.getName()).log(Level.SEVERE, null, ex);
                }   
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FileSaver.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            setVisible(false);
            dispose();
        }
        else
        {
            setVisible(false);
            dispose();
        }
        
        /*
        if (evt.getSource() == openButton) {
            fileChooser.getCurrentDirectory();

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                //This is where a real application would open the file.
                log.append("Opening: " + file.getName() + "." + newline);
            } else {
                log.append("Open command cancelled by user." + newline);
            }
        }
        */
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileBrowser dialog = new FileBrowser(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
